# Generated by Django 4.0.6 on 2022-08-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('phonenum', models.CharField(max_length=50)),
                ('areasop', models.TextField(blank=True, null=True)),
                ('consuls', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'وکلا',
            },
        ),
        migrations.CreateModel(
            name='OrderNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phonenum', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('chosenlawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lawyer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
